/**
 * Icons exported from Figma "Icons" frame (node 2667:1807).
 * Source: https://www.figma.com/design/0H1HmDgMDUddD0yCXV0WJj/Bambu-Slicer?node-id=2667-1807
 *
 * Two components in Figma share the name "assembly"; the chain-link variant is `assembly-linked`.
 * The `check2` symbol (node 2814:1447) could not be fetched via Figma MCP (invalid node) — re-export from Figma if needed.
 */
export const FIGMA_ICON_NAMES = [
  "arrow-down-wall",
  "arrow-refresh",
  "assembly",
  "assembly-linked",
  "auto",
  "boolean",
  "brim",
  "check",
  "chevron-down",
  "chevron-down-small",
  "chevron-right-small",
  "cloud-sync",
  "dots-vertical",
  "file",
  "fuzzy",
  "gear",
  "gear-filled",
  "globe",
  "layer-height",
  "layout",
  "light-bulb",
  "minus",
  "move",
  "paint",
  "place-on-face",
  "plus",
  "plus-square",
  "printer",
  "resize",
  "rotate",
  "ruler",
  "scissors",
  "seam",
  "share-os",
  "split",
  "support",
  "text",
  "x-close",
] as const;

export type FigmaIconName = (typeof FIGMA_ICON_NAMES)[number];

export const FIGMA_ICON_URLS: Record<FigmaIconName, string> = {
  "arrow-down-wall": "/assets/icons/arrow-down-wall.svg",
  "arrow-refresh": "/assets/icons/arrow-refresh.svg",
  assembly: "/assets/icons/assembly.svg",
  "assembly-linked": "/assets/icons/assembly-linked.svg",
  auto: "/assets/icons/auto.svg",
  boolean: "/assets/icons/boolean.svg",
  brim: "/assets/icons/brim.svg",
  check: "/assets/icons/check.svg",
  "chevron-down": "/assets/icons/chevron-down.svg",
  "chevron-down-small": "/assets/icons/chevron-down-small.svg",
  "chevron-right-small": "/assets/icons/chevron-right-small.svg",
  "cloud-sync": "/assets/icons/cloud-sync.svg",
  "dots-vertical": "/assets/icons/dots-vertical.svg",
  file: "/assets/icons/file.svg",
  fuzzy: "/assets/icons/fuzzy.svg",
  gear: "/assets/icons/gear.svg",
  "gear-filled": "/assets/icons/gear-filled.svg",
  globe: "/assets/icons/globe.svg",
  "layer-height": "/assets/icons/layer-height.svg",
  layout: "/assets/icons/layout.svg",
  "light-bulb": "/assets/icons/light-bulb.svg",
  minus: "/assets/icons/minus.svg",
  move: "/assets/icons/move.svg",
  paint: "/assets/icons/paint.svg",
  "place-on-face": "/assets/icons/place-on-face.svg",
  plus: "/assets/icons/plus.svg",
  "plus-square": "/assets/icons/plus-square.svg",
  printer: "/assets/icons/printer.svg",
  resize: "/assets/icons/resize.svg",
  rotate: "/assets/icons/rotate.svg",
  ruler: "/assets/icons/ruler.svg",
  scissors: "/assets/icons/scissors.svg",
  seam: "/assets/icons/seam.svg",
  "share-os": "/assets/icons/share-os.svg",
  split: "/assets/icons/split.svg",
  support: "/assets/icons/support.svg",
  text: "/assets/icons/text.svg",
  "x-close": "/assets/icons/x-close.svg",
};
